language: objective-c

before_install: 
  - brew update
  - brew install xctool

script: xctool -reporter pretty -project Objc-TDDFizzBuzz.xcodeproj -sdk iphonesimulator -scheme Objc-TDDFizzBuzz build test
